language: node_js
node_js:
  - 12
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
    - ls
#   - docker -v && docker-compose -v
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin

# install:
#   - docker-compose -f udagram-deployment/docker-compose-build.yaml build --parallel
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker-compose -f udagram-deployment/docker-compose-build.yaml push